repos:
    - repo: https://github.com/LiquidFun/aoc_tiles
      rev: 0.6.2
      hooks:
          - id: aoc-tiles
            args:
                - --auto-add-tiles-to-git=amend
                - --language-sorting=py,rs,jl,kt
                - --count-as-solved-when=on_leaderboard
                - --show-total-stars-for-all-years=yes